name: release-deb
on:
  push:
    tags: ['v*']

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      DEB_BUILD_OPTIONS: nocheck
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      - name: Install deb tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper dh-golang golang-any lintian
      - name: Set Debian version from tag
        id: v
        run: |
          TAG=${GITHUB_REF_NAME}
          UPVER=${TAG#v}
          echo "upver=$UPVER" >> $GITHUB_OUTPUT
      - name: Update changelog
        run: |
          dch --create -v "${{ steps.v.outputs.upver }}-1" --package llamapool \
            --distribution unstable "Release ${GITHUB_REF_NAME}"
          cat debian/changelog
      - name: Build (binary package only)
        env:
          DEB_BUILD_ARCH: ${{ matrix.arch }}
          GOARCH: ${{ matrix.arch }}
        run: |
          dpkg-buildpackage -b -us -uc
          mkdir -p out && mv ../*.deb out/
      - name: Lintian
        run: |
          lintian out/*.deb || true
      - name: Upload .deb to Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
