name: snapshot-deb
on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build-deb-snapshot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      - name: Install deb tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper dh-golang golang-any
      - name: Synthesize snapshot version
        id: v
        run: |
          DATE=$(date -u +%Y%m%d)
          SHA=$(git rev-parse --short HEAD)
          echo "ver=1.3.0~git${DATE}+${SHA}-1" >> $GITHUB_OUTPUT
      - name: Update changelog
        run: |
          dch --create -v "${{ steps.v.outputs.ver }}" --package llamapool \
            --distribution unstable "Snapshot build"
      - name: Build binary packages
        env:
          DEB_BUILD_ARCH: ${{ matrix.arch }}
          GOARCH: ${{ matrix.arch }}
        run: |
          dpkg-buildpackage -b -us -uc
          mkdir -p out && mv ../*.deb out/
      - uses: actions/upload-artifact@v4
        with:
          name: debs-${{ matrix.arch }}-${{ steps.v.outputs.ver }}
          path: out/*.deb
          retention-days: 14
